"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpRight, Check, Clock3, Copy, Link2, LoaderCircle, PackageCheck, Plus, Radar, RefreshCw, Search, ShieldCheck, Store, Tag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster, toast } from "sonner";

type Deal = { id: number; title: string; retailer: string; url: string; category: string; msrp_cents: number; price_cents: number; availability: string; condition: string | null; confidence_score: number; price_source: string; promo_code: string | null; promotion_text: string | null; checked_at: string; data_state: "LIVE" | "VERIFIED"; net_profit_cents: number | null; roi_percent: number | null; discount_percent: number; resale_comp_cents: number | null };
type Coverage = { tracked: number; retailers: number; qualified: number; updated_at: string };
type WebTool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => Promise<unknown> };
declare global { interface Document { modelContext?: { registerTool: (tool: WebTool, options?: { signal?: AbortSignal }) => void | Promise<void> } } }

const money = (cents: number | null) => cents == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: cents % 100 ? 2 : 0 }).format(cents / 100);
const timeAgo = (value: string | null) => { if (!value) return "Not yet verified"; const mins = Math.max(0, Math.round((Date.now() - new Date(`${value}Z`).getTime()) / 60000)); return mins < 2 ? "Verified just now" : mins < 60 ? `Verified ${mins}m ago` : `Verified ${Math.round(mins / 60)}h ago`; };

export default function DealDashboard() {
  const [deals, setDeals] = useState<Deal[]>([]); const [coverage, setCoverage] = useState<Coverage>({ tracked: 0, retailers: 0, qualified: 0, updated_at: "" });
  const [loading, setLoading] = useState(true); const [scanning, setScanning] = useState(false); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [category, setCategory] = useState("all"); const [open, setOpen] = useState(false);
  const firstDiscovery = useRef(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/deals", { cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json(); setDeals(body.deals ?? []); setCoverage(body.coverage ?? { tracked: 0, retailers: 0, qualified: 0, updated_at: "" }); if (!(body.deals ?? []).length && !firstDiscovery.current) { firstDiscovery.current = true; setScanning(true); await fetch("/api/discover", { method: "POST" }); const refreshed = await fetch("/api/deals", { cache: "no-store" }); if (refreshed.ok) { const next = await refreshed.json(); setDeals(next.deals ?? []); setCoverage(next.coverage ?? { tracked: 0, retailers: 0, qualified: 0, updated_at: "" }); } setScanning(false); } } catch { toast.error("Deal data is temporarily unavailable."); } finally { setLoading(false); } }, []);
  useEffect(() => { const kickoff = window.setTimeout(load, 0); return () => window.clearTimeout(kickoff); }, [load]);
  useEffect(() => { const timer = window.setInterval(load, 60_000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController();
    const tools: WebTool[] = [{ name: "read_qualified_deals", title: "Read qualified deals", description: "Return verified, in-stock gaming deals priced at MSRP or below.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, async execute() { return { count: deals.length, deals: deals.map(({ title, retailer, price_cents, msrp_cents, discount_percent, checked_at }) => ({ title, retailer, price_cents, msrp_cents, discount_percent, checked_at })) }; } }, { name: "scan_gaming_deals", title: "Scan gaming deals", description: "Refresh official gaming-retailer prices and return only qualifying deals.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true }, async execute() { const response = await fetch("/api/discover", { method: "POST" }); if (!response.ok) throw new Error("Scan failed"); const result = await response.json(); await load(); return result; } }];
    for (const tool of tools) Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => undefined); return () => lifecycle.abort();
  }, [deals, load]);
  const categories = useMemo(() => ["all", ...Array.from(new Set(deals.map((deal) => deal.category))).sort()], [deals]);
  const visible = useMemo(() => deals.filter((deal) => `${deal.title} ${deal.retailer} ${deal.category} ${deal.promo_code ?? ""}`.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || filter === "discounted" && deal.discount_percent > .01 || filter === "msrp" && Math.abs(deal.discount_percent) <= .01 || filter === "promos" && deal.promo_code) && (category === "all" || deal.category === category)), [category, deals, filter, query]);
  const discounted = deals.filter((deal) => deal.discount_percent > .01).length; const promos = deals.filter((deal) => deal.promo_code).length;
  async function scan() { setScanning(true); try { const response = await fetch("/api/discover", { method: "POST" }); if (!response.ok) throw new Error(); await load(); toast.success("Deal search finished. Only verified matches are shown."); } catch { toast.error("The search could not finish. Try again shortly."); } finally { setScanning(false); } }

  return <main className="min-h-screen bg-[#070b12] text-[#edf5ff]"><Toaster theme="dark" richColors /><div className="mx-auto max-w-[1320px] px-4 pb-12 pt-4 sm:px-7 lg:px-10">
    <header className="flex min-h-16 items-center justify-between border-b border-white/8 pb-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-cyan-300 text-slate-950 shadow-[0_0_32px_rgba(103,232,249,.18)]"><Radar className="size-5" /></div><div><div className="text-[17px] font-black tracking-tight">DEALSCOUT</div><div className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-500">Verified gaming prices</div></div></div><div className="flex items-center gap-2"><div className="mr-1 hidden items-center gap-2 text-xs font-semibold text-slate-400 md:flex"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]" />Checks every 30 minutes</div><Button onClick={scan} disabled={scanning} className="h-10 rounded-xl bg-cyan-300 px-4 font-extrabold text-slate-950 hover:bg-cyan-200">{scanning ? <LoaderCircle className="animate-spin" /> : <RefreshCw />}<span className="hidden sm:inline">Search now</span></Button><AddDeal open={open} setOpen={setOpen} onAdded={load} /></div></header>
    <section className="py-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-emerald-300/15 bg-emerald-300/[.06] px-3 py-1 text-xs font-bold text-emerald-300"><ShieldCheck className="size-3.5" />MSRP-or-less guarantee</div><h1 className="max-w-2xl text-3xl font-black tracking-[-.045em] sm:text-4xl">Real gaming deals. No overpriced listings.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Brand-new, in-stock products only. Every price must be verified and equal to or lower than MSRP.</p></div><div className="grid grid-cols-3 gap-2"><MiniStat value={String(deals.length)} label="Qualified" /><MiniStat value={String(discounted)} label="Discounted" /><MiniStat value={String(promos)} label="With codes" /></div></div><div className="mt-5 grid gap-2 rounded-2xl border border-white/8 bg-white/[.025] p-3 text-sm text-slate-400 sm:grid-cols-3"><Rule text="In stock and brand new" /><Rule text="Verified within 24 hours" /><Rule text={`${Math.max(coverage.retailers, 22)} retailer sources`} /></div></section>
    <section className="overflow-hidden rounded-[24px] border border-white/8 bg-[#0a1019] shadow-[0_22px_80px_rgba(0,0,0,.24)]"><div className="flex flex-col gap-4 border-b border-white/8 p-4 sm:p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><Tabs value={filter} onValueChange={setFilter}><TabsList className="h-auto max-w-full flex-wrap justify-start rounded-xl bg-white/5 p-1">{[["all", "All deals"], ["discounted", "Discounted"], ["msrp", "At MSRP"], ["promos", "Promo codes"]].map(([value, label]) => <TabsTrigger key={value} value={value} className="rounded-lg px-3 font-bold data-[state=active]:bg-slate-700 data-[state=active]:text-white sm:px-4">{label}</TabsTrigger>)}</TabsList></Tabs><div className="relative w-full md:w-80"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search deals, stores or codes" className="h-10 rounded-xl border-white/10 bg-white/5 pl-9" /></div></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((value) => <button key={value} onClick={() => setCategory(value)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold transition ${category === value ? "bg-cyan-300 text-slate-950" : "bg-white/5 text-slate-400 hover:bg-white/10 hover:text-white"}`}>{value === "all" ? "Every category" : value}</button>)}</div></div>
      {loading ? <div className="grid min-h-80 place-items-center"><LoaderCircle className="size-7 animate-spin text-cyan-300" /></div> : deals.length === 0 ? <EmptyState scanning={scanning} /> : visible.length === 0 ? <div className="grid min-h-64 place-items-center px-6 text-center text-slate-500">No verified deals match this filter.</div> : <div className="grid gap-3 p-3 sm:p-4 lg:grid-cols-2">{visible.map((deal) => <DealCard key={deal.id} deal={deal} />)}</div>}
    </section><footer className="mt-5 flex flex-col gap-1 px-1 text-xs leading-5 text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>Open-source · No affiliate ranking</span><span>Confirm price and code at checkout.</span></footer>
  </div></main>;
}

function DealCard({ deal }: { deal: Deal }) {
  const savings = Math.max(0, deal.msrp_cents - deal.price_cents); const discounted = savings > 0;
  async function copyPromo() { if (!deal.promo_code) return; try { await navigator.clipboard.writeText(deal.promo_code); toast.success(`Copied ${deal.promo_code}`); } catch { toast.error("Could not copy the code."); } }
  return <article className="group flex flex-col rounded-2xl border border-white/[.07] bg-[linear-gradient(150deg,rgba(255,255,255,.04),rgba(255,255,255,.012))] p-4 transition hover:border-cyan-300/20 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-black tracking-[.1em] ring-1 ${discounted ? "bg-emerald-400/10 text-emerald-300 ring-emerald-300/20" : "bg-cyan-400/10 text-cyan-200 ring-cyan-300/20"}`}>{discounted ? `${deal.discount_percent.toFixed(deal.discount_percent >= 10 ? 0 : 1)}% OFF` : "AT MSRP"}</span><span className="rounded-full bg-white/5 px-2.5 py-1 text-[11px] font-bold text-slate-400 ring-1 ring-white/10">{deal.category}</span></div><span className="flex shrink-0 items-center gap-1 text-xs font-bold text-emerald-300"><Check className="size-3.5" />In stock</span></div>
    <h2 className="mt-4 line-clamp-2 text-lg font-extrabold leading-6 tracking-[-.015em]">{deal.title}</h2><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Store className="size-3.5" />{deal.retailer}</span><span className="flex items-center gap-1.5"><Clock3 className="size-3.5" />{timeAgo(deal.checked_at)}</span></div>
    <div className="mt-5 flex items-end justify-between gap-4"><div><div className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Current price</div><div className="mt-1 text-3xl font-black tracking-[-.04em] text-white">{money(deal.price_cents)}</div></div><div className="text-right"><div className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">MSRP</div><div className={`mt-1 text-lg font-extrabold ${discounted ? "text-slate-500 line-through" : "text-cyan-300"}`}>{money(deal.msrp_cents)}</div></div></div>
    {discounted && <div className="mt-3 rounded-xl border border-emerald-300/15 bg-emerald-300/[.055] px-3 py-2 text-sm font-bold text-emerald-300">You save {money(savings)} · {deal.discount_percent.toFixed(1)}% below MSRP</div>}
    {deal.promo_code && <div className="mt-3 flex items-center justify-between gap-3 rounded-xl border border-violet-300/20 bg-violet-300/[.06] px-3 py-2.5"><div className="min-w-0"><div className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-[.12em] text-violet-300"><Tag className="size-3.5" />Promo code</div><div className="mt-1 truncate text-xs text-violet-100/60">{deal.promotion_text || "Official retailer offer"}</div></div><button onClick={copyPromo} aria-label={`Copy promo code ${deal.promo_code}`} className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-violet-300/15 px-3 py-2 font-mono text-sm font-black text-violet-100 transition hover:bg-violet-300/25"><Copy className="size-3.5" />{deal.promo_code}</button></div>}
    <div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Info label="Price source" value={deal.price_source} /><Info label="Confidence" value={`${deal.confidence_score}% verified`} /></div>
    {deal.net_profit_cents != null && <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 border-t border-white/[.06] pt-3 text-xs text-slate-500"><span>Resale estimate <strong className="text-slate-300">{money(deal.resale_comp_cents)}</strong></span><span>Projected net <strong className={deal.net_profit_cents > 0 ? "text-emerald-300" : "text-slate-300"}>{money(deal.net_profit_cents)}</strong></span>{deal.roi_percent != null && <span><strong className="text-slate-300">{deal.roi_percent.toFixed(1)}% ROI</strong></span>}</div>}
    <a href={deal.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white text-sm font-black text-slate-950 transition hover:bg-cyan-100">View deal at {deal.retailer}<ArrowUpRight className="size-4" /></a></article>;
}

function EmptyState({ scanning }: { scanning: boolean }) { return <div className="grid min-h-[340px] place-items-center p-8 text-center"><div className="max-w-md"><div className="mx-auto grid size-16 place-items-center rounded-2xl border border-cyan-300/15 bg-cyan-300/5">{scanning ? <LoaderCircle className="size-8 animate-spin text-cyan-300" /> : <PackageCheck className="size-8 text-cyan-300" />}</div><h2 className="mt-5 text-2xl font-black">{scanning ? "Searching retailers now" : "No verified deals right now"}</h2><p className="mt-2 leading-7 text-slate-400">Products appear only when they are new, in stock, recently verified, and priced at MSRP or less.</p></div></div>; }
function MiniStat({ value, label }: { value: string; label: string }) { return <div className="min-w-20 rounded-xl border border-white/8 bg-white/[.03] px-3 py-2 text-center"><div className="text-xl font-black">{value}</div><div className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</div></div>; }
function Rule({ text }: { text: string }) { return <div className="flex items-center gap-2"><Check className="size-4 shrink-0 text-emerald-400" /><span>{text}</span></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-black/20 px-3 py-2"><div className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-600">{label}</div><div className="mt-1 truncate font-bold text-slate-300">{value}</div></div>; }

function AddDeal({ open, setOpen, onAdded }: { open: boolean; setOpen: (value: boolean) => void; onAdded: () => Promise<void> }) {
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch("/api/deals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); toast.success("Product added. It will appear only if it qualifies."); setOpen(false); await onAdded(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add that product."); } finally { setSaving(false); } }
  return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="outline" size="icon" aria-label="Track a product" className="size-10 rounded-xl border-white/10 bg-white/5 hover:bg-white/10"><Plus /></Button></SheetTrigger><SheetContent className="border-white/10 bg-[#0a1019] text-white sm:max-w-md"><SheetHeader><SheetTitle className="text-2xl font-black text-white">Track a product</SheetTitle><SheetDescription className="leading-6 text-slate-400">Add an exact retailer product page. It stays hidden unless a new, in-stock price at MSRP or less is verified.</SheetDescription></SheetHeader><form onSubmit={submit} className="mt-7 space-y-5 px-4 pb-6"><Field label="Product URL"><Input name="url" required type="url" placeholder="https://retailer.com/product/..." /></Field><Field label="Product name"><Input name="title" required placeholder="RTX 5080 Founders Edition" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Official MSRP"><Input name="msrp" required inputMode="decimal" placeholder="999.99" /></Field><Field label="Expected resale"><Input name="resale" inputMode="decimal" placeholder="1450" /></Field></div><Field label="Category"><select name="category" className="h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm">{["GPU", "CPU", "Motherboard", "Memory", "Storage", "Monitor", "Gaming laptop", "Gaming desktop", "Console", "Handheld", "Controller", "Keyboard", "Mouse", "Headset", "Audio", "Streaming", "Networking", "VR", "Collectible", "Other"].map((value) => <option key={value} className="bg-slate-900">{value}</option>)}</select></Field><div className="rounded-xl border border-amber-300/15 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100/70"><strong className="text-amber-100">Use official MSRP.</strong> A crossed-out store price is not automatically MSRP.</div><Button disabled={saving} className="h-11 w-full rounded-xl bg-cyan-300 font-extrabold text-slate-950 hover:bg-cyan-200">{saving ? <LoaderCircle className="animate-spin" /> : <Link2 />}Add product</Button></form></SheetContent></Sheet>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="font-bold text-slate-300">{label}</Label>{children}</div>; }
