"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, AlertTriangle, BarChart3, CheckCircle2, ChevronRight, Clock3, Database, ExternalLink, Gauge, History, Link2, LoaderCircle, PackageCheck, Percent, Plus, Radar, RefreshCw, Search, ShieldCheck, Sparkles, Store, TrendingUp, Wifi, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster, toast } from "sonner";

type Deal = { id: number; title: string; retailer: string; url: string; category: string; msrp_cents: number; expected_resale_cents: number | null; price_cents: number | null; currency: string | null; availability: string | null; condition: string | null; confidence: number | null; confidence_score: number; price_source: string; checked_at: string | null; last_attempt_at: string | null; status: "buy" | "watch" | "skip" | "unknown"; data_state: "LIVE" | "VERIFIED" | "STALE" | "BLOCKED" | "PENDING"; net_profit_cents: number | null; roi_percent: number | null; discount_percent: number | null; lowest_price_cents: number | null; previous_price_cents: number | null; tax_cents: number | null; fees_cents: number | null; acquisition_cents: number | null; resale_comp_cents: number | null; resale_source: string; reference_source: string; deal_score: number; refresh_failed: boolean; check_count: number; error: string | null };
type WebTool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => Promise<unknown> };
declare global { interface Document { modelContext?: { registerTool: (tool: WebTool, options?: { signal?: AbortSignal }) => void | Promise<void> } } }
const money = (cents: number | null) => cents == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);
const timeAgo = (value: string | null, verified = true) => { if (!value) return "Never checked"; const mins = Math.max(0, Math.round((Date.now() - new Date(`${value}Z`).getTime()) / 60000)); const age = mins < 2 ? "just now" : mins < 60 ? `${mins}m ago` : `${Math.round(mins / 60)}h ago`; return `${verified ? "Verified" : "Attempted"} ${age}`; };

function Signal({ status }: { status: Deal["status"] }) {
  const map = { buy: ["BUY", "bg-emerald-400/12 text-emerald-300 ring-emerald-300/25"], watch: ["WATCH", "bg-amber-400/12 text-amber-200 ring-amber-300/25"], skip: ["SKIP", "bg-rose-400/12 text-rose-200 ring-rose-300/25"], unknown: ["VERIFY", "bg-slate-400/12 text-slate-300 ring-slate-300/20"] } as const;
  const [label, tone] = map[status];
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-black tracking-[.12em] ring-1 ${tone}`}>{label}</span>;
}

function DataState({ state }: { state: Deal["data_state"] }) {
  const map = { LIVE: [Wifi, "bg-emerald-400/12 text-emerald-300 ring-emerald-300/25"], VERIFIED: [ShieldCheck, "bg-cyan-400/12 text-cyan-200 ring-cyan-300/25"], STALE: [History, "bg-amber-400/12 text-amber-200 ring-amber-300/25"], BLOCKED: [WifiOff, "bg-rose-400/12 text-rose-200 ring-rose-300/25"], PENDING: [Clock3, "bg-slate-400/12 text-slate-300 ring-slate-300/20"] } as const;
  const [Icon, tone] = map[state];
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-black tracking-[.1em] ring-1 ${tone}`}><Icon className="size-3" />{state}</span>;
}

export default function DealDashboard() {
  const [deals, setDeals] = useState<Deal[]>([]); const [loading, setLoading] = useState(true); const [scanning, setScanning] = useState(false); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [category, setCategory] = useState("all"); const [open, setOpen] = useState(false);
  const firstDiscovery = useRef(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/deals", { cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json(); const nextDeals = body.deals ?? []; setDeals(nextDeals); if (!nextDeals.length && !firstDiscovery.current) { firstDiscovery.current = true; setScanning(true); const discover = await fetch("/api/discover", { method: "POST" }); if (discover.ok) { const result = await discover.json(); toast.success(`Found ${result.discovered + 3} starter and retailer listings.`); const refreshed = await fetch("/api/deals", { cache: "no-store" }); if (refreshed.ok) setDeals((await refreshed.json()).deals ?? []); } setScanning(false); } } catch { toast.error("Deal data is temporarily unavailable."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const timer = window.setInterval(load, 60_000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => {
    const timer = window.setInterval(async () => {
      try { await fetch("/api/discover", { method: "POST" }); await load(); } catch { /* next scheduled pass will retry */ }
    }, 30 * 60_000);
    return () => window.clearInterval(timer);
  }, [load]);
  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const tools: WebTool[] = [{
      name: "read_deal_signals", title: "Read deal signals", description: "Return the currently visible resale deal signals and their verification times.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true },
      async execute() { return { count: deals.length, deals: deals.map(({ title, retailer, status, price_cents, msrp_cents, checked_at }) => ({ title, retailer, status, price_cents, msrp_cents, checked_at })) }; },
    }, {
      name: "scan_tracked_products", title: "Scan tracked products", description: "Check all active retailer product pages now and refresh the visible deal signals.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true },
      async execute() { const response = await fetch("/api/discover", { method: "POST" }); if (!response.ok) throw new Error("Scan failed"); const result = await response.json(); await load(); return result; },
    }];
    for (const tool of tools) Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, [deals, load]);
  const categories = useMemo(() => ["all", ...Array.from(new Set(deals.map((deal) => deal.category))).sort()], [deals]);
  const visible = useMemo(() => deals.filter((deal) => `${deal.title} ${deal.retailer} ${deal.category}`.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || filter === "priced" && deal.price_cents != null || filter === "blocked" && deal.data_state === "BLOCKED" || filter === "buy" && deal.status === "buy") && (category === "all" || deal.category === category)), [category, deals, filter, query]);
  const stats = useMemo(() => ({ buy: deals.filter((d) => d.status === "buy").length, live: deals.filter((d) => d.data_state === "LIVE").length, priced: deals.filter((d) => d.price_cents != null).length, bestDiscount: deals.reduce((max, d) => Math.max(max, d.discount_percent ?? 0), 0) }), [deals]);
  async function scan() { setScanning(true); try { const response = await fetch("/api/discover", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(); toast.success(`Found ${body.discovered} new and checked ${body.checked} saved listings.`); await load(); } catch { toast.error("The scan could not finish. Try again in a moment."); } finally { setScanning(false); } }
  async function seed() { const response = await fetch("/api/seed", { method: "POST" }); if (response.ok) { toast.success("Starter watchlist added."); await load(); await scan(); } else toast.error("Starter targets could not be added."); }

  return <main className="min-h-screen bg-[#070b12] text-[#edf5ff]"><Toaster theme="dark" richColors /><div className="mx-auto max-w-[1500px] px-4 pb-12 pt-4 sm:px-7 lg:px-10">
    <header className="flex min-h-16 items-center justify-between border-b border-white/8 pb-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-cyan-300 text-slate-950 shadow-[0_0_32px_rgba(103,232,249,.18)]"><Radar className="size-5" /></div><div><div className="text-[17px] font-black tracking-tight">DEALSCOUT</div><div className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-500">Gaming tech intelligence</div></div></div><div className="flex items-center gap-2"><div className="mr-1 hidden items-center gap-2 text-xs font-semibold text-slate-400 sm:flex"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]" />30-minute scan active</div><Button onClick={scan} disabled={scanning} className="h-10 rounded-xl bg-cyan-300 px-4 font-extrabold text-slate-950 hover:bg-cyan-200">{scanning ? <LoaderCircle className="animate-spin" /> : <RefreshCw />}<span className="hidden sm:inline">Scan gaming tech</span></Button><AddDeal open={open} setOpen={setOpen} onAdded={load} /></div></header>
    <section className="py-5"><div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-black tracking-[-.03em] sm:text-3xl">Gaming deal command center</h1><p className="mt-1 text-sm text-slate-400">Verified prices stay visible even when a later retailer refresh fails.</p></div><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><Database className="size-4 text-cyan-300" />{deals.length} products tracked</div></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Buy signals" value={String(stats.buy)} icon={<Sparkles />} /><Metric label="Live now" value={String(stats.live)} icon={<Activity />} /><Metric label="Priced listings" value={`${stats.priced}/${deals.length}`} icon={<BarChart3 />} /><Metric label="Best discount" value={`${Math.round(stats.bestDiscount)}%`} icon={<Percent />} /></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 rounded-2xl border border-white/8 bg-white/[.025] px-4 py-3"><Guard text="Last good price survives failed refreshes" /><Guard text="Tax and marketplace fees shown separately" /><Guard text="Estimates never masquerade as live data" /></div></section>
    <section className="rounded-[26px] border border-white/8 bg-[#0a1019] shadow-[0_22px_80px_rgba(0,0,0,.24)]"><div className="flex flex-col gap-4 border-b border-white/8 p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><Tabs value={filter} onValueChange={setFilter}><TabsList className="h-10 rounded-xl bg-white/5 p-1">{[["all", "All"], ["buy", "Best"], ["priced", "Priced"], ["blocked", "Blocked"]].map(([v, l]) => <TabsTrigger key={v} value={v} className="rounded-lg px-4 font-bold data-[state=active]:bg-slate-700 data-[state=active]:text-white">{l}</TabsTrigger>)}</TabsList></Tabs><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products, categories, stores" className="h-10 rounded-xl border-white/10 bg-white/5 pl-9" /></div></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((value) => <button key={value} onClick={() => setCategory(value)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold transition ${category === value ? "bg-cyan-300 text-slate-950" : "bg-white/5 text-slate-400 hover:bg-white/10 hover:text-white"}`}>{value === "all" ? "Every category" : value}</button>)}</div></div>
      {loading ? <div className="grid min-h-80 place-items-center"><LoaderCircle className="size-7 animate-spin text-cyan-300" /></div> : deals.length === 0 ? <div className="grid min-h-[430px] place-items-center p-8 text-center"><div className="max-w-md"><div className="mx-auto grid size-16 place-items-center rounded-2xl border border-cyan-300/15 bg-cyan-300/5"><PackageCheck className="size-8 text-cyan-300" /></div><h2 className="mt-5 text-2xl font-black">Start with high-value targets</h2><p className="mt-2 leading-7 text-slate-400">Load a starter watchlist for Founders Edition GPUs, or add a supported retailer product URL.</p><Button onClick={seed} className="mt-6 h-11 rounded-xl bg-cyan-300 px-5 font-extrabold text-slate-950 hover:bg-cyan-200"><Sparkles />Load starter watchlist</Button></div></div> : visible.length === 0 ? <div className="grid min-h-72 place-items-center text-slate-500">No tracked products match this filter.</div> : <div className="divide-y divide-white/[.06]">{visible.map((deal) => <DealRow key={deal.id} deal={deal} />)}</div>}
    </section><footer className="mt-5 flex flex-col gap-2 px-1 text-xs leading-5 text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>Open-source under the MIT License · No affiliate ranking</span><span>Prices can change between checks. Confirm at checkout before buying.</span></footer>
  </div></main>;
}

function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-white/8 bg-[linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.015))] p-3 sm:p-4"><div className="mb-2 text-cyan-300 [&_svg]:size-4">{icon}</div><div className="text-xl font-black sm:text-2xl">{value}</div><div className="mt-1 text-[11px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</div></div>; }
function Guard({ text }: { text: string }) { return <div className="flex gap-2 text-xs leading-5 text-slate-400"><CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-emerald-400" /><span>{text}</span></div>; }
function DealRow({ deal }: { deal: Deal }) {
  const hasReference = deal.msrp_cents > 0; const stock = String(deal.availability ?? "").toLowerCase().includes("instock") ? "In stock" : deal.availability ? deal.availability.replace(/([a-z])([A-Z])/g, "$1 $2") : "Stock unknown";
  const retained = deal.refresh_failed && deal.price_cents != null; const priceNote = deal.price_cents == null ? deal.error ? "Retailer blocked all price sources" : "Waiting for a verified price" : retained ? "Last good price retained" : stock;
  return <article className="p-4 transition-colors hover:bg-white/[.018] sm:p-5"><div className="flex flex-col gap-4 xl:grid xl:grid-cols-[minmax(300px,1.2fr)_2fr_46px] xl:items-center">
    <div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><DataState state={deal.data_state} /><Signal status={deal.status} /><span className="text-xs font-bold text-slate-500">{deal.category}</span><span className="ml-auto text-xs font-black text-cyan-300 xl:hidden">Score {deal.deal_score}</span></div><a href={deal.url} target="_blank" rel="noreferrer" className="group flex items-start gap-2 text-base font-extrabold leading-6 hover:text-cyan-200"><span className="line-clamp-2">{deal.title}</span><ExternalLink className="mt-1 size-3.5 shrink-0 opacity-60" /></a><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Store className="size-3.5" />{deal.retailer}</span><span className="flex items-center gap-1.5"><Clock3 className="size-3.5" />{timeAgo(deal.price_cents != null ? deal.checked_at : deal.last_attempt_at, deal.price_cents != null)}</span>{retained && <span className="flex items-center gap-1 text-amber-300/80"><AlertTriangle className="size-3.5" />Refresh failed—history preserved</span>}</div></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><DataPoint label="Current" value={money(deal.price_cents)} sub={priceNote} emphasis /><DataPoint label="MSRP / reference" value={money(hasReference ? deal.msrp_cents : null)} sub={deal.reference_source} /><DataPoint label="Discount" value={deal.discount_percent == null ? "Not verified" : `${Math.abs(deal.discount_percent).toFixed(1)}% ${deal.discount_percent >= 0 ? "off" : "over"}`} sub={`Low seen ${money(deal.lowest_price_cents)}`} positive={(deal.discount_percent ?? 0) >= 10} /><DataPoint label="Projected net" value={deal.net_profit_cents == null ? "Not calculated" : money(deal.net_profit_cents)} sub={deal.roi_percent == null ? deal.resale_source : `${deal.roi_percent.toFixed(1)}% ROI`} positive={(deal.net_profit_cents ?? 0) > 0} /></div>
    <a href={deal.url} target="_blank" rel="noreferrer" aria-label={`Open ${deal.title}`} className="hidden size-11 place-items-center rounded-xl border border-white/8 text-slate-500 transition hover:border-cyan-300/30 hover:text-cyan-200 xl:grid"><ChevronRight className="size-4" /></a>
  </div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 border-t border-white/[.05] pt-3 text-[11px] font-semibold text-slate-600"><span>Confidence <strong className="text-slate-400">{deal.confidence_score}%</strong></span><span>Source <strong className="text-slate-400">{deal.price_source}</strong></span><span>Tax <strong className="text-slate-400">{deal.tax_cents == null ? "Unavailable" : money(deal.tax_cents)}</strong></span><span>Fees <strong className="text-slate-400">{deal.fees_cents == null ? "Unavailable" : money(deal.fees_cents)}</strong></span><span>Resale comp <strong className="text-slate-400">{deal.resale_comp_cents == null ? "Not verified" : money(deal.resale_comp_cents)}</strong></span><span>{deal.check_count} checks recorded</span></div></article>;
}
function DataPoint({ label, value, sub, positive, emphasis }: { label: string; value: string; sub: string; positive?: boolean; emphasis?: boolean }) { return <div className="min-w-0 rounded-xl border border-white/[.06] bg-black/15 p-3"><div className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-600">{label}</div><div className={`mt-1 truncate font-black ${emphasis ? "text-xl" : "text-base"} ${positive ? "text-emerald-300" : ""}`}>{value}</div><div className="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-500">{sub}</div></div>; }

function AddDeal({ open, setOpen, onAdded }: { open: boolean; setOpen: (v: boolean) => void; onAdded: () => Promise<void> }) {
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch("/api/deals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); toast.success("Product added to the scanner."); setOpen(false); await onAdded(); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not add that product."); } finally { setSaving(false); } }
  return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="outline" size="icon" className="size-10 rounded-xl border-white/10 bg-white/5 hover:bg-white/10"><Plus /></Button></SheetTrigger><SheetContent className="border-white/10 bg-[#0a1019] text-white sm:max-w-md"><SheetHeader><SheetTitle className="text-2xl font-black text-white">Track a product</SheetTitle><SheetDescription className="leading-6 text-slate-400">Use an exact Best Buy, Micro Center, NVIDIA, Newegg, Walmart, Amazon, Target, or GameStop product page.</SheetDescription></SheetHeader><form onSubmit={submit} className="mt-7 space-y-5 px-4 pb-6"><Field label="Product URL"><Input name="url" required type="url" placeholder="https://retailer.com/product/..." /></Field><Field label="Product name"><Input name="title" required placeholder="RTX 5080 Founders Edition" /></Field><div className="grid grid-cols-2 gap-3"><Field label="MSRP"><Input name="msrp" required inputMode="decimal" placeholder="999.99" /></Field><Field label="Expected resale"><Input name="resale" inputMode="decimal" placeholder="1450" /></Field></div><Field label="Category"><select name="category" className="h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm">{["GPU", "CPU", "Motherboard", "Memory", "Storage", "Monitor", "Gaming laptop", "Gaming desktop", "Console", "Handheld", "Controller", "Keyboard", "Mouse", "Headset", "Audio", "Streaming", "Networking", "VR", "Collectible", "Other"].map((v) => <option key={v} className="bg-slate-900">{v}</option>)}</select></Field><div className="rounded-xl border border-amber-300/15 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100/70"><strong className="text-amber-100">Verify MSRP.</strong> DealScout intentionally does not treat crossed-out prices as official MSRP.</div><Button disabled={saving} className="h-11 w-full rounded-xl bg-cyan-300 font-extrabold text-slate-950 hover:bg-cyan-200">{saving ? <LoaderCircle className="animate-spin" /> : <Link2 />}Add to scanner</Button></form></SheetContent></Sheet>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="font-bold text-slate-300">{label}</Label>{children}</div>; }
