import { db, retailerFromUrl, safeRetailerUrl } from "@/lib/deals";
export const dynamic = "force-dynamic";
export async function GET() {
  const result = await db().prepare(`SELECT p.*, o.price_cents, o.currency, o.availability, o.condition, o.confidence, o.checked_at, o.error FROM products p LEFT JOIN observations o ON o.id = (SELECT id FROM observations WHERE product_id = p.id ORDER BY checked_at DESC LIMIT 1) WHERE p.active = 1 ORDER BY CASE WHEN o.price_cents IS NOT NULL AND o.price_cents <= p.msrp_cents AND lower(coalesce(o.availability,'')) LIKE '%instock%' THEN 0 ELSE 1 END, o.checked_at DESC, p.created_at DESC`).all();
  const deals = (result.results as Record<string, unknown>[]).map((row) => { const price = row.price_cents as number | null; const msrp = row.msrp_cents as number; const resale = row.expected_resale_cents as number | null; const inStock = String(row.availability ?? "").toLowerCase().includes("instock"); const newItem = !row.condition || String(row.condition).toLowerCase().includes("new"); const acquisition = price == null ? null : Math.round(price * 1.06); const net = resale == null || acquisition == null ? null : Math.round(resale * (1 - .1325) - acquisition); const roi = net == null || acquisition == null ? null : net / acquisition * 100; const hasMsrp = msrp > 0; const status = price == null || !hasMsrp ? "unknown" : inStock && newItem && price <= msrp && (net == null || net >= 7500) && (roi == null || roi >= 15) ? "buy" : price <= msrp * 1.05 ? "watch" : "skip"; return { ...row, status, net_profit_cents: net, roi_percent: roi }; });
  return Response.json({ deals });
}
export async function POST(request: Request) {
  const body = await request.json() as Record<string, string>; let parsed: URL; try { parsed = safeRetailerUrl(body.url).url; } catch { return Response.json({ error: "Use an HTTPS product page from Best Buy, Micro Center, NVIDIA, Newegg, Walmart, Amazon, Target, or GameStop." }, { status: 400 }); }
  const msrp = Number(body.msrp); const resale = body.resale ? Number(body.resale) : null;
  if (!body.title?.trim() || !Number.isFinite(msrp) || msrp <= 0) return Response.json({ error: "Product name and a valid MSRP are required." }, { status: 400 });
  try { const result = await db().prepare("INSERT INTO products (title, retailer, url, category, msrp_cents, expected_resale_cents) VALUES (?, ?, ?, ?, ?, ?)").bind(body.title.trim().slice(0, 180), retailerFromUrl(parsed.toString()), parsed.toString(), (body.category || "Other").slice(0, 40), Math.round(msrp * 100), resale && Number.isFinite(resale) ? Math.round(resale * 100) : null).run(); return Response.json({ id: result.meta.last_row_id }, { status: 201 }); }
  catch (error) { if (String(error).toLowerCase().includes("unique")) return Response.json({ error: "That product page is already being tracked." }, { status: 409 }); return Response.json({ error: "The product could not be saved." }, { status: 500 }); }
}
