const SITE_URL = process.env.SITE_URL || "https://deal-scout.johnpz287.chatgpt.site";
const TOKEN = process.env.OIDC_TOKEN;
if (!TOKEN) throw new Error("OIDC_TOKEN is required");

const RETAILERS = new Map(Object.entries({
  "bestbuy.com":"Best Buy", "microcenter.com":"Micro Center", "nvidia.com":"NVIDIA", "newegg.com":"Newegg", "walmart.com":"Walmart", "amazon.com":"Amazon", "target.com":"Target", "gamestop.com":"GameStop",
  "bhphotovideo.com":"B&H Photo", "adorama.com":"Adorama", "dell.com":"Dell", "hp.com":"HP", "lenovo.com":"Lenovo", "asus.com":"ASUS", "acer.com":"Acer", "samsung.com":"Samsung", "lg.com":"LG", "sony.com":"Sony", "corsair.com":"Corsair", "logitechg.com":"Logitech G", "razer.com":"Razer", "woot.com":"Woot",
  "antonline.com":"Antonline", "centralcomputer.com":"Central Computers", "abt.com":"Abt", "costco.com":"Costco", "steelseries.com":"SteelSeries", "hyperx.com":"HyperX", "elgato.com":"Elgato", "nzxt.com":"NZXT", "msi.com":"MSI", "gigabyte.com":"Gigabyte", "viewsonic.com":"ViewSonic", "amd.com":"AMD", "intel.com":"Intel", "microsoft.com":"Microsoft Store", "playstation.com":"PlayStation Direct", "nintendo.com":"Nintendo", "meta.com":"Meta", "monoprice.com":"Monoprice", "pny.com":"PNY"
}));
const SOURCES = [
  ["https://www.bestbuy.com/site/searchpage.jsp?st=gaming+deals", "Best Buy"], ["https://www.microcenter.com/search/search_results.aspx?Ntt=gaming&storeid=061", "Micro Center"],
  ["https://www.newegg.com/Homepage-All-Deals/EventSaleStore/ID-9447", "Newegg"], ["https://www.walmart.com/search?q=gaming+tech+deals", "Walmart"],
  ["https://www.bhphotovideo.com/c/search?q=gaming%20monitor", "B&H Photo"], ["https://www.adorama.com/l/?searchinfo=gaming%20monitor", "Adorama"],
  ["https://www.dell.com/en-us/search/gaming%20laptop", "Dell"], ["https://www.hp.com/us-en/shop/slp/weekly-deals/gaming", "HP"],
  ["https://www.lenovo.com/us/en/search?text=gaming%20laptop", "Lenovo"], ["https://www.asus.com/us/searchresult?searchType=products&searchKey=gaming%20monitor", "ASUS"],
  ["https://www.samsung.com/us/search/searchMain/?listType=g&searchTerm=gaming%20monitor", "Samsung"], ["https://www.corsair.com/us/en/search?q=gaming", "Corsair"],
  ["https://www.logitechg.com/en-us/search.html?q=gaming", "Logitech G"], ["https://www.razer.com/search/gaming", "Razer"], ["https://www.woot.com/search?keyword=gaming", "Woot"],
  ["https://www.antonline.com/nvidia/geforce-rtx50/laptops", "Antonline"], ["https://www.centralcomputer.com/all-products/hardware/video-cards.html", "Central Computers"],
  ["https://www.abt.com/Computer-Monitors/c/442.html", "Abt"], ["https://www.costco.com/pc-gaming.html", "Costco"], ["https://steelseries.com/deals", "SteelSeries"],
  ["https://hyperx.com/collections/sale", "HyperX"], ["https://www.elgato.com/us/en/s/sale", "Elgato"], ["https://nzxt.com/collection/sale", "NZXT"],
  ["https://us-store.msi.com/Sale", "MSI"], ["https://store.gigabyte.us/", "Gigabyte"], ["https://www.viewsonic.com/us/products/shop/monitors/gaming.html", "ViewSonic"],
  ["https://www.amd.com/en/direct-buy/us", "AMD"], ["https://www.microsoft.com/en-us/store/b/sale", "Microsoft Store"], ["https://direct.playstation.com/en-us/deals", "PlayStation Direct"],
  ["https://www.nintendo.com/us/store/sales-and-deals/", "Nintendo"], ["https://www.meta.com/quest/", "Meta"], ["https://www.monoprice.com/category/computers-&-gaming", "Monoprice"],
  ["https://www.pny.com/promotions", "PNY"], ["https://store.acer.com/en-us/sale/monitor-sale", "Acer"], ["https://www.lg.com/us/promotions", "LG"], ["https://electronics.sony.com/sale/c/all-sale", "Sony"]
];
const KEYWORDS = /geforce|\brtx\b|radeon|ryzen|core ultra|gaming|oled|monitor|laptop|desktop|keyboard|mouse|headset|controller|playstation|\bps5\b|xbox|nintendo|switch|steam deck|rog ally|legion go|meta quest|ssd|nvme|ddr5|motherboard|limited edition/i;
const headers = { "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/128 Safari/537.36 DealScout/2.0", accept: "text/html,application/xhtml+xml" };
const clean = (s) => String(s || "").replace(/<[^>]*>/g, " ").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, " ").trim();
function retailerUrl(value, base) { const url = new URL(value, base); const host = url.hostname.toLowerCase().replace(/^www\./, ""); const entry = [...RETAILERS].find(([domain]) => host === domain || host.endsWith(`.${domain}`)); if (url.protocol !== "https:" || !entry) throw new Error("unsupported URL"); url.hash = ""; return { url, retailer: entry[1] }; }
async function getHtml(url, timeout = 15000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(url, { headers, redirect: "follow", signal: controller.signal }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.text(); } finally { clearTimeout(timer); } }
function walk(value, out) { if (!value || typeof value !== "object") return; if (Array.isArray(value)) return value.forEach((v) => walk(v, out)); out.push(value); Object.values(value).forEach((v) => walk(v, out)); }
function promo(html) { const text = clean(html); const matches = [...text.matchAll(/(?:promo(?:tional)?|coupon)\s+code(?:\s+is|\s*:)?\s+[“"']?([A-Z0-9][A-Z0-9-]{2,24})\b|\buse\s+code\s+[“"']?([A-Z0-9][A-Z0-9-]{2,24})\b/gi)]; const match = matches.find((candidate) => { const context = text.slice(Math.max(0, (candidate.index || 0) - 90), (candidate.index || 0) + candidate[0].length + 120); return !/expired|has ended|no longer valid|was valid/i.test(context); }); const code = match?.[1] || match?.[2]; return code ? { promo_code: code.toUpperCase(), promotion_text: match[0].slice(0, 180) } : { promo_code: null, promotion_text: null }; }
function offerFrom(html) {
  const objects = [];
  for (const match of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)) { try { walk(JSON.parse(match[1]), objects); } catch {} }
  const product = objects.find((o) => o["@type"] === "Product") || objects.find((o) => o.offers); const raw = product?.offers || objects.find((o) => o["@type"] === "Offer"); const offer = Array.isArray(raw) ? raw[0] : raw;
  const pageText = clean(html); const structuredAvailability = String(offer?.availability || "").split("/").pop();
  const negativeStock = /\bout of stock\b|\bsold out\b|currently unavailable|not available for (?:shipping|pickup|purchase)/i.test(pageText);
  const stockStatus = negativeStock ? "OUT_OF_STOCK" : /pre-?order/i.test(structuredAvailability + " " + pageText) ? "PREORDER" : /back-?order/i.test(structuredAvailability + " " + pageText) ? "BACKORDER" : /low stock|only \d+ left|few left/i.test(structuredAvailability + " " + pageText) ? "LOW_STOCK" : /instock|in stock|available for shipping|available for pickup/i.test(structuredAvailability + " " + pageText) ? "IN_STOCK" : "UNKNOWN";
  const availability = stockStatus;
  let priceValue = offer?.price ?? offer?.priceSpecification?.price; let price = typeof priceValue === "number" ? priceValue : Number(String(priceValue || "").replace(/[^0-9.]/g, "")); let confidence = structuredAvailability ? 98 : 90;
  if (!Number.isFinite(price) || price < 1) { const meta = html.match(/(?:itemprop=["']price["'][^>]*content=["']|property=["']product:price:amount["'][^>]*content=["'])([0-9,.]+)/i) || html.match(/(?:content=["'])([0-9,.]+)(?:["'][^>]*(?:itemprop=["']price["']|property=["']product:price:amount["']))/i); price = meta ? Number(meta[1].replace(/,/g, "")) : NaN; confidence = Math.min(confidence, 86); }
  if (!Number.isFinite(price) || price < 1 || price > 20000) return null;
  const condition = String(offer?.itemCondition || "NewCondition").split("/").pop();
  return { price_cents: Math.round(price * 100), effective_price_cents: Math.round(price * 100), currency: offer?.priceCurrency || "USD", availability, stock_status: stockStatus, stock_evidence: negativeStock ? "Explicit out-of-stock text" : structuredAvailability ? `Structured availability: ${structuredAvailability}` : stockStatus === "IN_STOCK" ? "Explicit stock or purchase signal" : "No reliable inventory signal", stock_confidence: negativeStock || structuredAvailability ? 98 : stockStatus === "IN_STOCK" ? 86 : 35, condition, confidence, title: typeof product?.name === "string" ? clean(product.name) : null, sku: product?.sku || product?.mpn || null, gtin: product?.gtin13 || product?.gtin12 || null, image_url: Array.isArray(product?.image) ? product.image[0] : product?.image || null, seller: offer?.seller?.name || null, ...promo(html) };
}
function category(title) { if (/rtx|geforce|radeon|graphics card/i.test(title)) return "GPU"; if (/monitor|display|oled/i.test(title)) return "Monitor"; if (/laptop|notebook/i.test(title)) return "Gaming laptop"; if (/desktop|gaming pc|prebuilt/i.test(title)) return "Gaming desktop"; if (/keyboard/i.test(title)) return "Keyboard"; if (/\bmouse\b/i.test(title)) return "Mouse"; if (/headset|headphone/i.test(title)) return "Headset"; if (/controller|gamepad/i.test(title)) return "Controller"; if (/ssd|nvme/i.test(title)) return "Storage"; if (/ddr|memory|ram/i.test(title)) return "Memory"; if (/motherboard/i.test(title)) return "Motherboard"; if (/console|playstation|xbox|switch/i.test(title)) return "Console"; return "Gaming hardware"; }
function discover(html, source) { const items = []; const seen = new Set(); for (const match of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]{8,800}?)<\/a>/gi)) { const title = clean(match[2]); if (!KEYWORDS.test(title) || title.length > 180 || /^(gaming|deals?|sale|shop|products?)$/i.test(title) || /water block|empty box|backplate|replacement fan|cooler only/i.test(title)) continue; try { const { url } = retailerUrl(match[1], source); if (seen.has(url.href)) continue; const start = match.index || 0; const card = clean(html.slice(Math.max(0, start - 300), start + 3500)); const prices = [...card.matchAll(/\$\s*([0-9]{1,5}(?:,[0-9]{3})*(?:\.\d{2})?)/g)].map((p) => Number(p[1].replace(/,/g, ""))).filter((p) => p >= 1 && p <= 20000); if (!prices.length) continue; const current = prices[0]; const known = /rtx\s*5080.*founders|founders.*rtx\s*5080/i.test(title) ? 99999 : /rtx\s*5090.*founders|founders.*rtx\s*5090/i.test(title) ? 199999 : 0; seen.add(url.href); items.push({ url: url.href, title, category: category(title), msrp_cents: known, msrp_source_url: known ? "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/" : null, price_cents: Math.round(current * 100), currency: "USD", availability: "UNKNOWN", stock_status: "UNKNOWN", stock_evidence: "Search listing is discovery evidence only", stock_confidence: 35, condition: "UnknownCondition", confidence: 72, source_type: "github-listing", source_url: source, ...promo(card) }); } catch {} } return items.slice(0, 8); }
async function post(observations) { if (!observations.length) return { accepted: 0 }; const response = await fetch(`${SITE_URL}/api/ingest`, { method: "POST", headers: { authorization: `Bearer ${TOKEN}`, "content-type": "application/json" }, body: JSON.stringify({ observations: observations.slice(0, 80) }) }); if (!response.ok) throw new Error(`Ingest failed ${response.status}: ${await response.text()}`); return response.json(); }

const dealsResponse = await fetch(`${SITE_URL}/api/targets`, { headers: { accept: "application/json", authorization: `Bearer ${TOKEN}` } }); if (!dealsResponse.ok) throw new Error(`Could not load tracked targets: ${dealsResponse.status}`); const targets = (await dealsResponse.json()).targets || [];
const observations = []; const discoveries = [];
for (let i = 0; i < targets.length; i += 6) await Promise.all(targets.slice(i, i + 6).map(async (deal) => { try { const html = await getHtml(deal.url); const offer = offerFrom(html); if (offer) observations.push({ id: deal.id, ...offer, source_type: "github-direct", source_url: deal.url }); } catch {} }));
for (let i = 0; i < SOURCES.length; i += 5) await Promise.all(SOURCES.slice(i, i + 5).map(async ([source]) => { try { const found = discover(await getHtml(source, 12000), source); discoveries.push(...found); observations.push(...found); } catch {} }));
const directDiscoveries = [...new Map(discoveries.filter((item) => item.msrp_cents > 0).map((item) => [item.url, item])).values()].slice(0, 36);
for (let i = 0; i < directDiscoveries.length; i += 6) await Promise.all(directDiscoveries.slice(i, i + 6).map(async (item) => { try { const offer = offerFrom(await getHtml(item.url)); if (offer) observations.push({ ...item, ...offer, availability: offer.availability, source_type: "github-direct", source_url: item.url }); } catch {} }));
const unique = [...new Map(observations.map((item) => [`${item.id || item.url}|${item.price_cents}`, item])).values()].slice(0, 80); const result = await post(unique);
console.log(JSON.stringify({ tracked: targets.length, extracted: unique.length, ...result }));
